version: '1.0'
volumes:
  rabbitmq_data:
  redis_data:
  nacos_data:
services:
  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  redis:
    image: redis:alpine
    container_name: knowledge_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  nacos:
    image: nacos/nacos-server:v2.1.2
    container_name: nacos
    ports:
      - "8848:8848"
    volumes:
      - nacos_data:/home/nacos/init.d/custom.properties
      - nacos_data:/home/nacos/logs
      - nacos_data:/home/nacos/data
      - nacos_data:/home/nacos/plugins
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
